### PR TITLE
kvdpa: support for adding a new VdpaDevice

### PR DESCRIPTION
**Pull request by lmilleri**
This PR extends the govdpa library with the capability of creating a new VDPA device.
In detail, this is the newly introduced CLI command:

CLI command: kvdpa-cli add [mgmtdev] [dev]
       mgmtdev: the VDPA management device (e.g. pci/0000:65:00.2)
       dev:     the VDPA device (e.g. vdpa1)

### CODE REVIEW

**Comment by amorenoz** [comment]
A fewl nits:
- Commits typically need to have a Signed-Of-By (git commit -s)
- Commits need a commit message explaining the change
- PRs also need description

**Comment by amorenoz** [comment]
Code looks good to me. Do you want me to merge it and use this branch as working branch until we sent it all to the official repo or do you want to send this to the npwg directly?

**Comment by lmilleri** [comment]
I'll update the commit/PR description and send it again. I think it'll be easy to merge it in your repo

**Comment by lmilleri** [comment]
No longer needed, changes already merged to master

**Pull request closed without merging**
